2024-09-17 at 14:07:37 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:07:37 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-17 at 14:07:37 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-17 at 14:07:37 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-17 at 14:07:40 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:07:40 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-17 at 14:07:40 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-17 at 14:07:40 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-17 at 14:07:40 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:07:40 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-17 at 14:07:40 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-17 at 14:07:40 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-17 at 14:07:41 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:07:41 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-17 at 14:07:41 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-17 at 14:07:41 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-17 at 14:07:41 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:07:41 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-17 at 14:07:41 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-17 at 14:07:41 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-17 at 14:07:42 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:07:42 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-17 at 14:07:42 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-17 at 14:07:42 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-17 at 14:07:44 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 20. Recuperados: 20. Min_id: 7784938969
2024-09-17 at 14:07:45 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 0. Recuperados: 30. Min_id: 7784938969
2024-09-17 at 14:07:45 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 401: {"error":"This method requires an authenticated user"}
2024-09-17 at 14:07:45 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-17 at 14:07:45 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-17 at 14:07:45 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-17 at 14:07:46 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 110. Recuperados: 30. Min_id: 7784938969
2024-09-17 at 14:07:47 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 110. Recuperados: 30. Min_id: 7784938969
2024-09-17 at 14:07:47 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 20. Recuperados: 20. Min_id: 7784938969
2024-09-17 at 14:07:59 CEST WARN  org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl - RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataWriter is already registered.  2nd registration is being ignored.
2024-09-17 at 14:08:09 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:08:09 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-17 at 14:08:09 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-17 at 14:08:09 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-17 at 14:08:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:08:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-17 at 14:08:10 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-17 at 14:08:10 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-17 at 14:08:10 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi - getTruthsocialAccountList. Cantidad: 0. Recuperados: 67. Max_id: null
2024-09-17 at 14:08:11 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 422: {"errors":[{"error_code":"RECORD_INVALID","error_message":"Text can't be blank","error_field":null}],"error_message":"Text can't be blank","error_code":"RECORD_INVALID","error":"Text can't be blank"}
2024-09-17 at 14:08:11 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-17 at 14:08:11 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-17 at 14:08:11 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-17 at 14:08:11 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-17 at 14:08:11 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi - getTruthsocialAccountList. Cantidad: 0. Recuperados: 40. Max_id: 112990391031747445
2024-09-17 at 14:08:12 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi - getTruthsocialAccountList. Cantidad: 0. Recuperados: 67. Max_id: null
2024-09-17 at 14:08:12 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:08:12 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-17 at 14:08:12 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-17 at 14:08:12 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-17 at 14:08:13 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:08:13 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-17 at 14:08:13 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-17 at 14:08:13 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-17 at 14:08:15 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:08:15 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-17 at 14:08:15 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-17 at 14:08:15 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-17 at 14:08:15 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:08:15 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-17 at 14:08:15 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-17 at 14:08:15 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-17 at 14:08:16 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:08:16 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-17 at 14:08:16 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-17 at 14:08:16 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-17 at 14:08:16 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-17 at 14:08:16 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-17 at 14:08:16 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-17 at 14:08:16 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
