2024-09-25 at 08:51:05 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:05 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-25 at 08:51:05 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-25 at 08:51:05 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-25 at 08:51:08 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:08 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-25 at 08:51:08 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-25 at 08:51:08 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-25 at 08:51:08 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:08 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-25 at 08:51:08 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-25 at 08:51:08 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-25 at 08:51:09 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:09 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-25 at 08:51:09 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-25 at 08:51:09 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-25 at 08:51:09 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:09 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-25 at 08:51:09 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-25 at 08:51:09 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-25 at 08:51:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:10 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-25 at 08:51:10 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-25 at 08:51:10 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-25 at 08:51:11 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 20. Recuperados: 20. Min_id: 7910985304
2024-09-25 at 08:51:12 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 0. Recuperados: 30. Min_id: 7910985304
2024-09-25 at 08:51:12 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 401: {"error":"This method requires an authenticated user"}
2024-09-25 at 08:51:12 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-25 at 08:51:12 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-25 at 08:51:12 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-25 at 08:51:13 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 110. Recuperados: 30. Min_id: 7910985304
2024-09-25 at 08:51:13 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 110. Recuperados: 30. Min_id: 7910985304
2024-09-25 at 08:51:14 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 20. Recuperados: 20. Min_id: 7910985304
2024-09-25 at 08:51:24 CEST WARN  org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl - RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataWriter is already registered.  2nd registration is being ignored.
2024-09-25 at 08:51:41 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:41 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 08:51:41 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 08:51:41 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 08:51:41 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:41 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-25 at 08:51:41 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-25 at 08:51:41 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-25 at 08:51:42 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi - getTruthsocialAccountList. Cantidad: 0. Recuperados: 67. Max_id: null
2024-09-25 at 08:51:42 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 422: {"errors":[{"error_code":"RECORD_INVALID","error_message":"Text can't be blank","error_field":null}],"error_message":"Text can't be blank","error_code":"RECORD_INVALID","error":"Text can't be blank"}
2024-09-25 at 08:51:42 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-25 at 08:51:42 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-25 at 08:51:42 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-25 at 08:51:42 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-25 at 08:51:42 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi - getTruthsocialAccountList. Cantidad: 0. Recuperados: 40. Max_id: 112990391031747445
2024-09-25 at 08:51:43 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi - getTruthsocialAccountList. Cantidad: 0. Recuperados: 67. Max_id: null
2024-09-25 at 08:51:43 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:43 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-25 at 08:51:43 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-25 at 08:51:43 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-25 at 08:51:43 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:43 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-25 at 08:51:43 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-25 at 08:51:43 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-25 at 08:51:46 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-25 at 08:51:47 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 08:51:47 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 08:51:47 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 08:51:47 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 09:57:13 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:13 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-25 at 09:57:13 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-25 at 09:57:13 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60. Se obtuvo el código de error: 404
2024-09-25 at 09:57:15 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:15 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-25 at 09:57:15 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-25 at 09:57:15 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/lookup. Se obtuvo el código de error: 404
2024-09-25 at 09:57:16 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:16 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-25 at 09:57:16 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-25 at 09:57:16 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/followers. Se obtuvo el código de error: 404
2024-09-25 at 09:57:16 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:16 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-25 at 09:57:16 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-25 at 09:57:16 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/unfollow. Se obtuvo el código de error: 404
2024-09-25 at 09:57:17 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:17 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-25 at 09:57:17 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-25 at 09:57:17 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/following. Se obtuvo el código de error: 404
2024-09-25 at 09:57:17 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:17 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-25 at 09:57:17 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-25 at 09:57:17 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialAccountApiImpl: Error ejecutando: https://truthsocial.com/api/v1/accounts/1125349753AAABBB60/follow. Se obtuvo el código de error: 404
2024-09-25 at 09:57:19 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 20. Recuperados: 20. Min_id: 7910985304
2024-09-25 at 09:57:20 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 0. Recuperados: 30. Min_id: 7910985304
2024-09-25 at 09:57:20 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 401: {"error":"This method requires an authenticated user"}
2024-09-25 at 09:57:20 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-25 at 09:57:20 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-25 at 09:57:20 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl: Error ejecutando: https://truthsocial.com/api/v1/notifications. Se obtuvo el código de error: 401
2024-09-25 at 09:57:21 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 110. Recuperados: 30. Min_id: 7910985304
2024-09-25 at 09:57:21 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 110. Recuperados: 30. Min_id: 7910985304
2024-09-25 at 09:57:22 CEST INFO  com.laboratorio.truthsocialapiinterface.impl.TruthsocialNotificationApiImpl - getAllNotifications. Cantidad: 20. Recuperados: 20. Min_id: 7910985304
2024-09-25 at 09:57:32 CEST WARN  org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl - RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.multipart.MultipartFormDataWriter is already registered.  2nd registration is being ignored.
2024-09-25 at 09:57:49 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:49 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 09:57:49 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 09:57:49 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 09:57:50 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:50 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-25 at 09:57:50 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-25 at 09:57:50 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/favourited_by. Se obtuvo el código de error: 404
2024-09-25 at 09:57:51 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 422: {"errors":[{"error_code":"RECORD_INVALID","error_message":"Text can't be blank","error_field":null}],"error_message":"Text can't be blank","error_code":"RECORD_INVALID","error":"Text can't be blank"}
2024-09-25 at 09:57:51 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-25 at 09:57:51 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-25 at 09:57:51 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-25 at 09:57:51 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses. Se obtuvo el código de error: 422
2024-09-25 at 09:57:52 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:52 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-25 at 09:57:52 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-25 at 09:57:52 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialBaseApi: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQQ109412553445428617/reblogged_by. Se obtuvo el código de error: 404
2024-09-25 at 09:57:53 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:53 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-25 at 09:57:53 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-25 at 09:57:53 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/reblog. Se obtuvo el código de error: 404
2024-09-25 at 09:57:55 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:55 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-25 at 09:57:55 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-25 at 09:57:55 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unreblog. Se obtuvo el código de error: 404
2024-09-25 at 09:57:55 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:55 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-25 at 09:57:55 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-25 at 09:57:55 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/favourite. Se obtuvo el código de error: 404
2024-09-25 at 09:57:56 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:56 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-25 at 09:57:56 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-25 at 09:57:56 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/QQ112836040801154212/unfavourite. Se obtuvo el código de error: 404
2024-09-25 at 09:57:56 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Respuesta del error 404: {"errors":[{"error_code":"NOT_FOUND","error_message":"Record not found","error_field":null}],"error_message":"Record not found","error_code":"NOT_FOUND","error":"Record not found"}
2024-09-25 at 09:57:56 CEST ERROR com.laboratorio.clientapilibrary.impl.ApiClientImpl - Error: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 09:57:56 CEST ERROR com.laboratorio.clientapilibrary.exceptions.ApiClientException - Error com.laboratorio.clientapilibrary.impl.ApiClientImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
2024-09-25 at 09:57:56 CEST ERROR com.laboratorio.truthsocialapiinterface.exception.TruthsocialApiException - Error com.laboratorio.truthsocialapiinterface.impl.TruthsocialStatusApiImpl: Error ejecutando: https://truthsocial.com/api/v1/statuses/1125AXR11TRE9WQW63. Se obtuvo el código de error: 404
